### ISSUE TITLE
Vagrantfile for testing purposes

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#459]
## Description

We are close to reach the MVP validation stage for the upcoming release 5.0.0. In this release, we include 3 new plugins to wazuh-indexer: `wazuh-indexer-setup`, `wazuh-indexer-command-manager` and `wazuh-indexer-reports-scheduler`.

In order to tests these plugins work as expected under a build of Wazuh Indexer, we need to develop a testing environment that fit our needs. This issue aims to develop a Vagrantfile that prepares this environment in a reusable manner.

Our testing environment will consist of 2x Wazuh Indexer nodes forming a cluster. The installation of the Wazuh Indexer package itself will be performed manually, as the packages need to be generated beforehand using our regular packaging building process. The Vagrant environment will prepare the required infrastructure to set up the cluster, including:

- Static IP binding
- Installation of the operating system.
- Certificates generation.

## Implementation restrictions

- One of the nodes runs under Ubuntu 22.04.
- One of the nodes runs under RHEL 9.
- The environment runs under `libvirt` virtualization API.
- The firewall is disabled on both nodes.
- The nodes use static IP binding as defined below.

```yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "192.168.56.10"
    - name: node-2
      ip: "192.168.56.11"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  # server:
    #- name: wazuh-1
    # ip: "<wazuh-manager-ip>"
    #  node_type: master

  # Wazuh dashboard nodes
  # dashboard:
    #- name: dashboard
    #  ip: "<dashboard-node-ip>"
```
