### ISSUE TITLE
Migrate Smoke Tests to GitHub Actions Native Container Support

### ISSUE THREAD

**Issue by Jorgesnchz** [wazuh/wazuh-indexer#982]
## Description

After reviewing the GitHub documentation, it has been concluded that the smoke tests, which are currently being executed in Docker using an action called `addnab/docker-run-action`, could be migrated to utilize GitHub's native functionality for[ running jobs within a container](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container).

Example of its use:
```
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

```

## Functional requirements

- All the functionalities remain tested

## Implementation restrictions

- Delete all references to `addnab/docker-run-action`
