### ISSUE TITLE
Indexer-Dashboard performance tests under OpenSearch 3.0

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#998]
## Description

With the Wazuh Indexer and Wazuh Dashboard now working on top of OpenSearch 3, we need to compare the performance of these components with a previous build using OpenSearch 2.x, verifying that:

1. Indexing throughput and search latency must not regress compared with 2.x baselines under the same workload.
2. Memory footprint should not increase.

## Plan

For Wazuh Indexer (both, using 2.x and 3.x baselines):
  * Owner: @wazuh/devel-xdrsiem-indexer 
  * Teams involved: @wazuh/devel-xdrsiem-indexer 

- [x] Measure idle CPU, RAM and Disk usage.
- [x] Throughput and search latency test
  - 1. Prepare a workload for the test (using our events generators. ~1K events)
  - 2. Bulk index the workload (write down the ingestion time).
  - 3. Perform a search query (write down the response time).

For Wazuh Dashboard (both, using 2.x and 3.x baselines):
  * Owner: @wazuh/devel-xdrsiem-dashboard 
  * Teams involved: @wazuh/devel-xdrsiem-dashboard 

- [x] Measure idle CPU, RAM and Disk usage.
- [x] Login time.
- [x] Page load time (same page on both tests, e.g: Vulnerability Detection.

**Comment by AlexRuiz7** [comment]
Take this test as reference: https://github.com/wazuh/wazuh-indexer-plugins/issues/359#issuecomment-2792403539

**Comment by f-galland** [comment]
## Wazuh Indexer

<details>
<summary>
<h3>2.x baseline metrics</h3>
</summary>

### Node 1

#### Cluster version

```shellsession
[root@ip-172-31-38-23 ~]# curl -sku admin:admin https://172.31.38.23:9200/_cluster/stats | jq '.nodes.versions'
[
  "2.19.2"
]
```

#### Filesystem usage:

```shellsession
[root@ip-172-31-38-23 ~]# curl -sku admin:admin https://172.31.38.23:9200/_cluster/stats | jq '.nodes.fs'
{
  "total_in_bytes": 63214497792,
  "free_in_bytes": 55917187072,
  "available_in_bytes": 55900409856,
  "cache_reserved_in_bytes": 0
}
```

#### JVM Heap usage:

```shellsession
[root@ip-172-31-38-23 ~]# curl -sku admin:admin https://172.31.38.23:9200/_cluster/stats | jq '.nodes.jvm'
{
  "max_uptime_in_millis": 773866,
  "versions": [
    {
      "version": "21.0.6",
      "vm_name": "OpenJDK 64-Bit Server VM",
      "vm_version": "21.0.6+7-LTS",
      "vm_vendor": "Eclipse Adoptium",
      "bundled_jdk": true,
      "using_bundled_jdk": true,
      "count": 2
    }
  ],
  "mem": {
    "heap_used_in_bytes": 890393760,
    "heap_max_in_bytes": 2147483648
  },
  "threads": 110
}
```

#### Total memory usage:

```shellsession
[root@ip-172-31-38-23 ~]# curl -sku admin:admin https://172.31.38.23:9200/_cluster/stats | jq '.nodes.os'
{
  "available_processors": 8,
  "allocated_processors": 8,
  "names": [
    {
      "name": "Linux",
      "count": 2
    }
  ],
  "pretty_names": [
    {
      "pretty_name": "Ubuntu 22.04.2 LTS",
      "count": 1
    },
    {
      "pretty_name": "Amazon Linux 2",
      "count": 1
    }
  ],
  "mem": {
    "total_in_bytes": 16376119296,
    "free_in_bytes": 7649943552,
    "used_in_bytes": 8726175744,
    "free_percent": 47,
    "used_percent": 53
  }
}
```

#### CPU usage and open file descriptors:

> [!NOTE]
> The cpu usage metric varies very rapidly, so I've included output from `pidstat` here as well

```shellsession
[root@ip-172-31-38-23 ~]# curl -sku admin:admin https://172.31.38.23:9200/_cluster/stats | jq '.nodes.process'
{
  "cpu": {
    "percent": 4
  },
  "open_file_descriptors": {
    "min": 677,
    "max": 678,
    "avg": 677
  }
}

[root@ip-172-31-38-23 ~]# pidstat -C java -h -I -u -r -d
Linux 5.10.210-201.852.amzn2.aarch64 (ip-172-31-38-23.ec2.internal) 	06/26/2025 	_aarch64_	(4 CPU)

#      Time   UID       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM   kB_rd/s   kB_wr/s kB_ccwr/s  Command
 1750952517   995      4784    0.54    0.03    0.00    0.14     0     62.90      0.01 4984588 1533152  19.27      0.00      0.87      0.41  java

```

### Node 2

#### Filesystem usage:

```shellsession
root@ip-172-31-45-54:~# curl -ku admin:admin https://172.31.45.54:9200/_cluster/stats | jq '.nodes.fs'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9850  100  9850    0     0   663k      0 --:--:-- --:--:-- --:--:--  687k
{
  "total_in_bytes": 63214497792,
  "free_in_bytes": 55914704896,
  "available_in_bytes": 55897927680,
  "cache_reserved_in_bytes": 0
}

```

#### JVM Heap usage:

```shellsession
root@ip-172-31-45-54:~# curl -sku admin:admin https://172.31.45.54:9200/_cluster/stats | jq '.nodes.jvm'
{
  "max_uptime_in_millis": 1500691,
  "versions": [
    {
      "version": "21.0.6",
      "vm_name": "OpenJDK 64-Bit Server VM",
      "vm_version": "21.0.6+7-LTS",
      "vm_vendor": "Eclipse Adoptium",
      "bundled_jdk": true,
      "using_bundled_jdk": true,
      "count": 2
    }
  ],
  "mem": {
    "heap_used_in_bytes": 586843888,
    "heap_max_in_bytes": 2147483648
  },
  "threads": 108
}

```

#### Total memory usage:

```shellsession
root@ip-172-31-45-54:~# curl -sku admin:admin https://172.31.45.54:9200/_cluster/stats | jq '.nodes.os'
{
  "available_processors": 8,
  "allocated_processors": 8,
  "names": [
    {
      "name": "Linux",
      "count": 2
    }
  ],
  "pretty_names": [
    {
      "pretty_name": "Ubuntu 22.04.2 LTS",
      "count": 1
    },
    {
      "pretty_name": "Amazon Linux 2",
      "count": 1
    }
  ],
  "mem": {
    "total_in_bytes": 16376119296,
    "free_in_bytes": 7589277696,
    "used_in_bytes": 8786841600,
    "free_percent": 46,
    "used_percent": 54
  }
}

```

#### CPU usage and open file descriptors:

> [!NOTE]
> The cpu usage metric varies very rapidly, so I've included output from `pidstat` here as well

```shellsession
root@ip-172-31-45-54:~# curl -sku admin:admin https://172.31.45.54:9200/_cluster/stats | jq '.nodes.process'
{
  "cpu": {
    "percent": 1
  },
  "open_file_descriptors": {
    "min": 676,
    "max": 679,
    "avg": 677
  }
}


root@ip-172-31-45-54:~# pidstat -C java -h -I -u -r -d
Linux 5.19.0-1025-aws (ip-172-31-45-54) 	06/26/25 	_x86_64_	(4 CPU)

# Time        UID       PID    %usr %system  %guest   %wait    %CPU   CPU  minflt/s  majflt/s     VSZ     RSS   %MEM   kB_rd/s   kB_wr/s kB_ccwr/s iodelay  Command
15:53:03      998      4493    0.50    0.02    0.00    0.00    0.13     2     33.65      0.03 4976152 1523936  18.97      0.00      0.89      0.37       0  java

```

</details>

**Comment by Tostti** [comment]
## Wazuh dashboard 

<details>
<summary>
<h3>2.x baseline metrics</h3>
</summary>

**Resources usage (idle)**
Took a measurement every second for 60 seconds with `ps -<PID> -o %cpu,rss`

CPU (%) usage: Avg = 0.467% | Min = 0.400% | Max = 0.500%
RAM (GB) usage: Avg = 0.218 GB | Min = 0.212 GB | Max = 0.234 GB

**Storage usage**
```console
root@ip-172-31-47-154:/home/admin# du -s /usr/share/wazuh-dashboard/
1149080 /usr/share/wazuh-dashboard/
root@ip-172-31-47-154:/home/admin# du -s /etc/wazuh-dashboard/
32      /etc/wazuh-dashboard/
```

**Login page load time:** 7,23s
**Login time:** 10,74s
</details>

**Comment by QU3B1M** [comment]
LGTM!

---

I've tested the Wazuh Indexer `5.0.0` package on `Alma Linux 9` on `aarch64` architecture _(Amazon Linux was not available)_ and it seems to work correctly.
```console
# systemctl status wazuh-indexer.service
● wazuh-indexer.service - wazuh-indexer
     Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; prese>
     Active: active (running) since Fri 2025-06-27 21:22:53 UTC; 5s ago
       Docs: https://documentation.wazuh.com
   Main PID: 6737 (java)
      Tasks: 73 (limit: 50368)
     Memory: 1.3G
        CPU: 15.068s
     CGroup: /system.slice/wazuh-indexer.service
             └─6737 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearc>

Jun 27 21:22:46 localhost.localdomain systemd[1]: Starting wazuh-indexer...
Jun 27 21:22:47 localhost.localdomain wazuh-indexer[6737]: WARNING: Using incubato>
Jun 27 21:22:47 localhost.localdomain wazuh-indexer[6737]: WARNING: Unknown module>
Jun 27 21:22:53 localhost.localdomain systemd[1]: Started wazuh-indexer.
```
The `opensearch.yml` is correctly formatted
```yaml
network.host: "0.0.0.0"
node.name: "node-1"
cluster.initial_cluster_manager_nodes:
- "node-1"
#- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
#discovery.seed_hosts:
#  - "node-1-ip"
#  - "node-2-ip"
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

```

It could be an error on that specific installation.
